// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Nipaa is a osu!droid server built by dasher
	 */
	description: string
}

export type TranslationFunctions = {
	/**
	 * Nipaa is a osu!droid server built by dasher
	 */
	description: () => LocalizedString
}

export type Formatters = {}
