// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Nipaa! is an osu!droid server built by Dasher
	 */
	description: string
	/**
	 * Accuracy
	 */
	accuracy: string
	/**
	 * Playcount
	 */
	playCount: string
	/**
	 * Performance
	 */
	performance: string
	/**
	 * Nipaa is a osu!droid server which has goals to provide a functioning in-game dpp leaderboard whilst providing a user friendly website interface, nipaa has by now almost every feature you would expect from iBancho with a few exceptions, such as not being able to upload your beloved avatar for now! but fear not, this project is open source and atleast being try to be mantained by me... (Dasher)
	 */
	about: string
	/**
	 * Leaderboard
	 */
	leaderboard: string
	/**
	 * Home
	 */
	home: string
}

export type TranslationFunctions = {
	/**
	 * Nipaa! is an osu!droid server built by Dasher
	 */
	description: () => LocalizedString
	/**
	 * Accuracy
	 */
	accuracy: () => LocalizedString
	/**
	 * Playcount
	 */
	playCount: () => LocalizedString
	/**
	 * Performance
	 */
	performance: () => LocalizedString
	/**
	 * Nipaa is a osu!droid server which has goals to provide a functioning in-game dpp leaderboard whilst providing a user friendly website interface, nipaa has by now almost every feature you would expect from iBancho with a few exceptions, such as not being able to upload your beloved avatar for now! but fear not, this project is open source and atleast being try to be mantained by me... (Dasher)
	 */
	about: () => LocalizedString
	/**
	 * Leaderboard
	 */
	leaderboard: () => LocalizedString
	/**
	 * Home
	 */
	home: () => LocalizedString
}

export type Formatters = {}
