import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <div>
      <Head>
        <title>Nipaa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {session ? (
          <>
            <p>{`Logged as ${session.user?.name}`}</p>
            <button
              onClick={async () => {
                await signOut();
              }}
            >
              Sign out
            </button>
          </>
        ) : (
          <>
            <p>Not signed in</p>
            <button
              onClick={async () => {
                await signIn();
              }}
            >
              Sign in
            </button>
          </>
        )}
      </main>
    </div>
  );
};

export default Home;
